module.exports = {
  rules: {
    "array-bracket-newline": [2, "consistent"],
    "array-bracket-spacing": [2, "never"],
    "array-element-newline": 0,
    "arrow-parens": [2, "as-needed"],
    "arrow-spacing": [2, { before: true, after: true }],
    "block-spacing": [2, "never"],
    "brace-style": [2, "1tbs", { allowSingleLine: false }],
    "comma-dangle": [2, "never"],
    "comma-spacing": [2, { before: false, after: true }],
    "comma-style": [2, "last", { exceptions: { NewExpression: false } }],
    "computed-property-spacing": [2, "never", { enforceForClassMembers: true }],
    "dot-location": [2, "property"],
    "eol-last": 2,
    "func-call-spacing": [2, "never"],
    "function-call-argument-newline": 0,
    "function-paren-newline": 0,
    "generator-star-spacing": [2, "after"],
    "implicit-arrow-linebreak": [2, "beside"],
    indent: [
      2,
      2,
      { SwitchCase: 1, ignoreComments: false, ImportDeclaration: 1, flatTernaryExpressions: false },
    ],
    "jsx-quotes": [2, "prefer-double"],
    "key-spacing": [2, { beforeColon: false, afterColon: true }],
    "keyword-spacing": 2,
    "line-comment-position": 0,
    "linebreak-style": [2, "unix"],
    "lines-around-comment": 0,
    "lines-between-class-members": [2, "always"],
    "max-len": [
      2,
      {
        code: 120,
        tabWidth: 4,
        ignoreStrings: true,
        ignoreComments: true,
        ignoreRegExpLiterals: true,
      },
    ],
    "max-statements-per-line": [2, { max: 1 }],
    "multiline-ternary": 0,
    "new-parens": 2,
    "no-extra-parens": [2, "functions"],
    "no-mixed-spaces-and-tabs": [2, "smart-tabs"],
    "no-multi-spaces": 2,
    "no-multiple-empty-lines": [2, { max: 1 }],
    "no-tabs": 2,
    "no-trailing-spaces": [2, { skipBlankLines: false, ignoreComments: true }],
    "nonblock-statement-body-position": 0,
    "object-curly-newline": 0,
    "object-curly-spacing": [2, "never"],
    "object-property-newline": [2, { allowAllPropertiesOnSameLine: false }],
    "operator-linebreak": 0,
    "padded-blocks": [2, "never"],
    "padding-line-between-statements": [
      2,
      { blankLine: "always", prev: "*", next: "return" },
      { blankLine: "always", prev: "directive", next: "*" },
      { blankLine: "any", prev: "directive", next: "directive" },
      { blankLine: "any", prev: ["const", "let", "var"], next: "*" },
      { blankLine: "always", prev: "iife", next: "*" },
      { blankLine: "always", prev: "*", next: "iife" },
    ],
    quotes: [2, "single", { avoidEscape: true, allowTemplateLiterals: true }],
    "rest-spread-spacing": [2, "never"],
    semi: 2,
    "semi-spacing": [2, { before: false, after: true }],
    "semi-style": [2, "last"],
    "space-before-blocks": 2,
    "space-before-function-paren": [
      2,
      { anonymous: "never", named: "never", asyncArrow: "always" },
    ],
    "space-in-parens": [2, "never"],
    "space-infix-ops": 2,
    "space-unary-ops": [2, { words: true, nonwords: false }],
    "switch-colon-spacing": [2, { after: true, before: false }],
    "template-curly-spacing": [2, "never"],
    "template-tag-spacing": [2, "never"],
    "unicode-bom": [2, "never"],
    "wrap-iife": [2, "inside", { functionPrototypeMethods: true }],
    "wrap-regex": 0,
    "yield-star-spacing": [2, "after"],
  },
};
